#!/usr/bin/env ruby

require_relative '../lib/todo_buster/finder'
require_relative '../lib/todo_buster/configuration'

TodoBuster.configure

puts "valid period is: #{TodoBuster.configuration.valid_period}"

finder = TodoBuster::Finder.new
finder.find_todos
