#!/usr/bin/env ruby

require_relative '../lib/todo_buster/finder'
require_relative '../lib/todo_buster/configuration'

TodoBuster.configure

parser = OptionParser.new do|opts|
  opts.banner = 'Usage: bust_todos [options]'
  opts.on('-v n', '--valid-period=n', 'TODO validity period in ActiveSupport format (i.e. 1.day, 2.years etc.)') do |valid_period|
    begin
      number_of_units, unit_type = valid_period.split '.'
      TodoBuster.configuration.valid_period = number_of_units.to_i.send unit_type
    rescue
      puts 'Invalid period'
      puts opts
      exit
    end
  end

  opts.on('-h', '--help', 'Displays Help') do
    puts opts
    exit
  end
end
parser.parse!

finder = TodoBuster::Finder.new

finder.search.length > 0 ? exit(1) : exit(0)
