#!/usr/bin/env ruby

require 'optparse'
require 'active_support/all'
require_relative '../lib/todo_buster/finder'
require_relative '../lib/todo_buster/configuration'
require_relative '../lib/todo_buster/configurators/valid_period_configurator'
require_relative '../lib/todo_buster/configurators/reports_configurator'
require_relative '../lib/todo_buster/configurators/output_dir_configurator'
require_relative '../lib/todo_buster/configurators/file_masks_configurator'

TodoBuster.configure

parser = OptionParser.new do|opts|
  opts.banner = 'Usage: bust_todos [options]'

  opts.on('-v n', '--valid-period=n', 'TODO validity period in ActiveSupport format (i.e. 1.day, 2.years etc.)') do |valid_period|
    TodoBuster::Configurators::ValidPeriodConfigurator.new.apply_config(valid_period) { puts opts }
  end

  opts.on('-r n', '--reports=n', 'Comma separated list of reports (currently supporting CONSOLE and HTML)') do |reporters|
    TodoBuster::Configurators::ReportsConfigurator.new.apply_config(reporters) { puts opts }
  end

  opts.on('-o n', '--output-dir=n', 'Output directory for HTML reports') do |output_dir|
    TodoBuster::Configurators::OutputDirConfigurator.new.apply_config(output_dir) { puts opts }
  end

  opts.on('-f n', '--file-masks=n', 'Comma separated list of file masks to scan') do |file_masks|
    TodoBuster::Configurators::FileMasksConfigurator.new.apply_config(file_masks) { puts opts }
  end

  opts.on('-h', '--help', 'Displays Help') do
    puts opts
    exit
  end
end
parser.parse!

finder = TodoBuster::Finder.new

finder.search.length > 0 ? exit(1) : exit(0)
